FROM ubuntu:trusty
MAINTAINER RUDDRA <me@ruddra.com>
# Update the sources list
RUN apt-get update; \
  apt-get install -y build-essential supervisor nginx \
  python python-dev python3-dev python3-pip \
  python3-setuptools libmemcached-dev zlib1g-dev; \
  mkdir -p /app/src
# Add config dir
ADD config/ /config
# RUN python3 -m easy_install mysql-connector-python; pip3 install -r /config/requirements.pip
RUN pip3 install -r /config/requirements.pip
EXPOSE 8080
ENTRYPOINT ["/usr/bin/supervisord", "-c", "/config/supervisord.conf"]
