nginx:
  image: nginx:latest
  container_name: ng01
  links:
    - firefist:firefist
  ports:
    - "8080:80"
  volumes:
    - ./src:/app/src

firefist:
  build: .
  container_name: ff01
  links:
    - psql:psql
  volumes:
    - ./src:/app/src
  ports:
    - "8000:8000"

psql:
  container_name: psql
  image: postgres:latest
  ports:
    - "3306:3306"



