nginx:
  image: nginx:latest
  container_name: ng01
  links:
    - firefist:firefist
  ports:
    - "7070:8000"
  volumes:
    - ./src:/app/src
    - ./config/nginx:/etc/nginx/conf.d

firefist:
  build: .
  container_name: ff01
  links:
    - psql:psql
  volumes:
    - ./src:/app/src
    - ./logs:/app/src/firefist/logs
  expose:
    - "8000"

psql:
  container_name: ps01
  image: postgres:latest
  ports:
    - "3306:3306"
  environment:
    - POSTGRES_PASSWORD=ROOT
    - POSTGRES_USER=ROOT




